# Site settings
# in the templates available like {{ site.myvariable }}.
title: OKIME EMIKO - Warsaw based visual artist, cinematographer, video director and VJ.
email: your-email@domain.com
brand: OKIME EMIKO
headline: Warsaw based visual artist, cinematographer, video director and VJ.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emiliagumanska.com" # the base hostname & protocol for your site
copyright: 

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
Website: https://emiliagumanska.com/vj/
Facebook: https://www.facebook.com/emikovj
Twitter: 
Youtube: https://www.youtube.com/@vjemiko/featured
Instagram: https://www.instagram.com/emiko__okime/

# Tracking
googleAnalitycsID: UA-83933844-1

