# Site settings
# in the templates available like {{ site.myvariable }}.
title: Melbourne based video artist.
email: 
brand:
headline: Melbourne based video artist.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.skynoise.net" # the base hostname & protocol for your site
copyright: 

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
Website: 


# Tracking
googleAnalitycsID: 

